### ISSUE TITLE
XK.XK_X is used for both self.x and self.r

### ISSUE THREAD

**Issue by muffinmad** [DylanHamer/ZeroWM#1]
https://github.com/DylanHamer/ZeroWM/blob/4c90e24536c1c00926a26fce9e4a4854534c88a1/ZeroWM.py#L129

**Comment by DylanHamer** [comment]
Ah! That's why I've been having that damn bug! Thank you! Keen observation skills! Fixing now.

**Comment by muffinmad** [comment]
I suggest to replace all ```set(code for code, index in self.display.keysym_to_keycodes(XK.XK_Left))``` with:
```
def get_codes(key):
    return set(code for code, index in self.display.keysym_to_keycodes(key))

self.left = get_codes(XK.XK_Left)
...
self.r = get_codes(XK.XK_R)
````

**Comment by DylanHamer** [comment]
That's  a much better idea. I'll fix that soon. Thanks!
